
import React, { useRef, useMemo, useState, useEffect } from 'react';
import { toPng } from 'html-to-image';
import { Customer, UtangRecord, BranchConfig } from '../types';

interface WeeklyReportModalProps {
  records: UtangRecord[];
  customers: Customer[];
  branch: BranchConfig;
  onClose: () => void;
}

// --- Date Helper Functions ---
const getWeekId = (dateStr: string): string => {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) return "Invalid Date";
    const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
    d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));
    const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
    const weekNo = Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);
    return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, '0')}`;
};

const getWeekDateRange = (weekId: string): string => {
    if (!weekId.includes('-W')) return "Invalid Week ID";
    const [year, weekNoStr] = weekId.split('-W');
    const weekNo = parseInt(weekNoStr, 10);
    const d = new Date(Date.UTC(parseInt(year, 10), 0, 1 + (weekNo - 1) * 7));
    const day = d.getUTCDay() || 7;
    d.setUTCDate(d.getUTCDate() + 4 - day);
    const weekStart = new Date(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() - 3);
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    
    const options: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' };
    return `${weekStart.toLocaleDateString('en-US', options)} - ${weekEnd.toLocaleDateString('en-US', { ...options, year: 'numeric' })}`;
};


// --- Thermal Print Component ---
const ThermalLedger: React.FC<{ customerData: any; customerName: string | null; branch: BranchConfig; sortedWeeks: string[] }> = ({ customerData, customerName, branch, sortedWeeks }) => {
    if (!customerData || !customerName) return null;
    
    // Flatten all records and sort chronologically for a continuous ledger
    const allRecords = sortedWeeks
        .flatMap(weekId => customerData.weeklyData[weekId].records)
        .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    return (
        <div className="thermal-print-container font-mono text-black bg-white p-2" style={{ width: '58mm', boxSizing: 'border-box', fontSize: '10px' }}>
            <div className="text-center">
                <p className="font-bold uppercase">{branch.name}</p>
                <p className="text-xs">CUSTOMER LEDGER</p>
                <p className="text-xs">{new Date().toLocaleString()}</p>
            </div>
            <div className="border-t border-b border-dashed border-black my-2 py-1">
                <p>CUSTOMER: {customerName.toUpperCase()}</p>
                <p className="font-bold">BALANCE: P{customerData.totalOutstanding.toFixed(2)}</p>
            </div>
            <div className="text-xs">
                {allRecords.map(record => (
                    <div key={record.id} className="my-2 border-b border-dashed border-black pb-2">
                        <p>DATE: {new Date(record.date).toLocaleString()}</p>
                        <p>REF: {record.id.slice(0, 8).toUpperCase()}</p>
                        <div className="pl-2">
                            {record.items.map((item, idx) => (
                                <p key={idx}>- {item.quantity}x {item.name} @ {item.price.toFixed(2)}</p>
                            ))}
                        </div>
                        <div className="text-right">
                            <p>TOTAL: P{record.totalAmount.toFixed(2)}</p>
                            <p>PAID: P{record.paidAmount.toFixed(2)}</p>
                            <p className="font-bold">{record.isPaid ? 'STATUS: PAID' : `BAL: P${(record.totalAmount - record.paidAmount).toFixed(2)}`}</p>
                        </div>
                    </div>
                ))}
            </div>
            <div className="text-center text-xs mt-4">
                <p>*** END OF STATEMENT ***</p>
                <p className="mt-2">Generated by Sari-Sari Debt Pro</p>
            </div>
        </div>
    );
};


// --- Main Component ---
const WeeklyReportModal: React.FC<WeeklyReportModalProps> = ({ records, customers, branch, onClose }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [selectedCustomerName, setSelectedCustomerName] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [printMode, setPrintMode] = useState<'a4' | 'thermal' | null>(null);

  useEffect(() => {
    // Add/remove class from body for print styling
    if (printMode) {
      document.body.classList.add(`print-mode-${printMode}`);
    } else {
      document.body.classList.remove('print-mode-a4', 'print-mode-thermal');
    }
  }, [printMode]);

  useEffect(() => {
    const afterPrint = () => {
      setPrintMode(null);
    };
    window.addEventListener('afterprint', afterPrint);
    return () => window.removeEventListener('afterprint', afterPrint);
  }, []);

  const customerLedgerData = useMemo(() => {
    const dataByCustomer: Record<string, {
      totalOutstanding: number;
      weeklyData: Record<string, { dateRange: string; debtIncurred: number; records: UtangRecord[] }>;
    }> = {};

    customers.forEach(customer => {
      const customerRecords = records.filter(r => r.customerName === customer.name);
      if (customerRecords.length === 0) return;

      const totalOutstanding = customerRecords.filter(r => !r.isPaid).reduce((sum, r) => sum + (r.totalAmount - r.paidAmount), 0);
      
      const weeklyData: Record<string, { dateRange: string; debtIncurred: number; records: UtangRecord[] }> = {};

      customerRecords.forEach(record => {
        const weekId = getWeekId(record.date);
        if (!weeklyData[weekId]) {
          weeklyData[weekId] = { dateRange: getWeekDateRange(weekId), debtIncurred: 0, records: [] };
        }
        weeklyData[weekId].debtIncurred += record.totalAmount;
        weeklyData[weekId].records.push(record);
      });

      // Sort records within each week
      Object.values(weeklyData).forEach(week => {
        week.records.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
      });

      dataByCustomer[customer.name] = { totalOutstanding, weeklyData };
    });

    return dataByCustomer;
  }, [records, customers]);
  
  const customerList = useMemo(() => {
    return Object.entries(customerLedgerData)
      .map(([name, data]: [string, { totalOutstanding: number }]) => ({ name, totalOutstanding: data.totalOutstanding }))
      .sort((a, b) => b.totalOutstanding - a.totalOutstanding);
  }, [customerLedgerData]);

  const filteredCustomerList = useMemo(() => {
    if (!searchQuery) return customerList;
    return customerList.filter(c => c.name.toLowerCase().includes(searchQuery.toLowerCase()));
  }, [customerList, searchQuery]);

  const selectedCustomerData = selectedCustomerName ? customerLedgerData[selectedCustomerName] : null;
  const sortedWeeks = selectedCustomerData ? Object.keys(selectedCustomerData.weeklyData).sort().reverse() : [];

  const handlePrint = (mode: 'a4' | 'thermal') => {
    setPrintMode(mode);
    setTimeout(() => {
      window.print();
    }, 100); // Allow state to update and trigger CSS
  };

  const handleSaveImage = async () => {
    if (!reportRef.current || isSaving) return;
    setIsSaving(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 300));
      const dataUrl = await toPng(reportRef.current, {
        cacheBust: true, pixelRatio: 2, backgroundColor: '#ffffff',
        width: 794, height: reportRef.current.scrollHeight,
        style: { height: 'auto', minHeight: '1123px', transform: 'none', margin: '0', boxShadow: 'none' }
      });
      const link = document.createElement('a');
      link.download = `SukiLedger_${(selectedCustomerName || '').replace(/\s+/g, '_')}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) { console.error('Failed to save report image', err); } 
    finally { setIsSaving(false); }
  };

  return (
    <div className="fixed inset-0 bg-slate-950/90 backdrop-blur-md flex items-center justify-center z-[500] p-0 md:p-4 animate-in fade-in">
      <div className="bg-[#0f172a] w-full h-full md:h-[90vh] md:max-w-7xl md:rounded-[2.5rem] shadow-2xl overflow-hidden border-0 md:border border-white/10 flex flex-col md:flex-row">
        
        {/* Sidebar */}
        <div className="w-full md:w-80 bg-[#1e293b] p-6 border-r border-white/5 flex flex-col shrink-0">
            <div className="mb-6">
                <h3 className="text-xl font-black text-white uppercase tracking-tight">Weekly Ledger</h3>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mt-1">Suki Accounts</p>
            </div>
            
            <input 
              type="text"
              placeholder="Search Suki..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="w-full h-12 bg-[#0f172a] rounded-xl px-4 text-xs font-bold text-white outline-none focus:ring-2 focus:ring-primary/50 transition mb-4"
            />
            
            <div className="flex-1 overflow-y-auto custom-scrollbar -mr-3 pr-3 space-y-2">
              {filteredCustomerList.map(customer => (
                <button 
                  key={customer.name}
                  onClick={() => setSelectedCustomerName(customer.name)}
                  className={`w-full p-4 rounded-2xl text-left transition-all ${selectedCustomerName === customer.name ? 'bg-primary text-white shadow-lg' : 'bg-[#0f172a] hover:bg-slate-800'}`}
                >
                   <p className="font-black text-xs uppercase truncate">{customer.name}</p>
                   <p className={`text-[10px] font-bold ${selectedCustomerName === customer.name ? 'text-white/70' : 'text-slate-400'}`}>
                     Balance: ₱{customer.totalOutstanding.toLocaleString(undefined, {minimumFractionDigits: 2})}
                   </p>
                </button>
              ))}
            </div>
            
            <div className="mt-6 space-y-2">
              <div className="grid grid-cols-2 gap-2">
                <button onClick={() => handlePrint('a4')} className="py-3 bg-white/10 text-white rounded-xl font-black uppercase text-[10px] tracking-widest hover:bg-white/20 transition">Print A4</button>
                <button onClick={() => handlePrint('thermal')} className="py-3 bg-white/10 text-white rounded-xl font-black uppercase text-[10px] tracking-widest hover:bg-white/20 transition">Print Thermal</button>
              </div>
              <button onClick={handleSaveImage} disabled={isSaving || !selectedCustomerData} className="w-full py-3 bg-primary text-white rounded-xl font-black uppercase text-[10px] tracking-widest hover:bg-primary-dark transition disabled:opacity-50">
                 {isSaving ? 'Saving...' : 'Save as Image'}
              </button>
              <button onClick={onClose} className="w-full py-3 bg-white/5 text-slate-400 rounded-xl font-black uppercase text-[10px] tracking-widest hover:bg-rose-500 hover:text-white transition">Close</button>
            </div>
        </div>

        {/* Preview */}
        <div className="flex-1 bg-slate-200 dark:bg-slate-900/50 overflow-y-auto p-4 md:p-8 flex justify-center custom-scrollbar">
          {!selectedCustomerData ? (
            <div className="flex items-center justify-center h-full text-center">
               <div>
                  <span className="text-6xl">👈</span>
                  <p className="mt-4 font-bold text-slate-500">Select a customer to view their ledger.</p>
               </div>
            </div>
          ) : (
            <div className="w-full flex flex-col items-center">
              <div ref={reportRef} className="bg-white text-slate-900 shadow-2xl relative a4-print-container" style={{ width: '210mm', minHeight: '297mm', padding: '15mm', boxSizing: 'border-box' }}>
                <div className="w-full h-full border-2 border-slate-300 p-4">
                  <header className="text-center border-b-2 border-slate-800 pb-4 mb-6">
                    <h1 className="text-2xl font-black uppercase tracking-tighter">{branch.name}</h1>
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mt-1">Customer Ledger Statement</p>
                    <p className="text-[9px] font-bold text-slate-400 mt-2">{new Date().toLocaleDateString()}</p>
                  </header>

                  <main className="space-y-8">
                    <section className="break-inside-avoid page-break-inside-avoid">
                      <div className="flex justify-between items-start bg-slate-100 p-4 rounded-lg border-b-2 border-slate-800">
                         <div>
                            <p className="text-[10px] font-bold uppercase text-slate-500">Statement For:</p>
                            <h2 className="text-lg font-black uppercase tracking-widest text-slate-900">{selectedCustomerName}</h2>
                         </div>
                         <div className="text-right">
                            <p className="text-[10px] font-bold uppercase text-slate-500">Outstanding Balance</p>
                            <p className="text-xl font-black text-rose-600">₱{selectedCustomerData.totalOutstanding.toLocaleString(undefined, {minimumFractionDigits: 2})}</p>
                         </div>
                      </div>
                      
                      <div className="space-y-4 p-2 mt-4">
                        {sortedWeeks.map(weekId => {
                           const week = selectedCustomerData.weeklyData[weekId];
                           return (
                             <details key={weekId} className="pl-4 break-inside-avoid" open>
                               <summary className="font-bold text-xs text-slate-600 uppercase mb-2 cursor-pointer list-none flex justify-between items-center py-2 border-b border-slate-200">
                                 <span>{week.dateRange}</span>
                                 <span className="font-black text-slate-800">Debt Added: ₱{week.debtIncurred.toLocaleString(undefined, {minimumFractionDigits: 2})}</span>
                               </summary>
                               <div className="space-y-3 pt-3 border-l-2 border-slate-200 pl-4">
                                 {week.records.map(record => (
                                   <div key={record.id} className="text-[10px] break-inside-avoid bg-slate-50 p-3 rounded-lg">
                                     <div className="flex justify-between items-center">
                                       <p className="font-bold text-slate-500">{new Date(record.date).toLocaleString('en-US', { dateStyle: 'short', timeStyle: 'short' })}</p>
                                       <span className={`text-[9px] font-black px-2 py-0.5 rounded-full ${record.isPaid ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>
                                         {record.isPaid ? 'Paid' : 'Unpaid'}
                                       </span>
                                     </div>
                                     <ul className="list-disc pl-5 text-slate-700 my-2 columns-2 gap-x-4">
                                       {record.items.map((item, idx) => <li key={idx}>({item.quantity}x) {item.name}</li>)}
                                     </ul>
                                     <div className="text-right font-black text-slate-800 border-t border-slate-200 pt-1 mt-1">Total: ₱{record.totalAmount.toFixed(2)}</div>
                                   </div>
                                 ))}
                               </div>
                             </details>
                           );
                        })}
                      </div>
                    </section>
                  </main>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
      
      {/* Hidden Thermal Print Component */}
      <ThermalLedger customerData={selectedCustomerData} customerName={selectedCustomerName} branch={branch} sortedWeeks={sortedWeeks} />

       <style>{`
        .thermal-print-container {
          display: none; /* Hidden by default */
        }

        @media print {
          body * {
            visibility: hidden;
          }

          /* --- A4 Print Mode --- */
          body.print-mode-a4 .a4-print-container,
          body.print-mode-a4 .a4-print-container * {
            visibility: visible;
          }
          body.print-mode-a4 .a4-print-container {
            position: absolute !important; left: 0 !important; top: 0 !important;
            width: 210mm !important; min-height: 297mm !important;
            margin: 0 !important; padding: 15mm !important;
            box-shadow: none !important; border: none !important;
            background-color: white !important;
          }
          body.print-mode-a4 .page-break-inside-avoid {
            break-inside: avoid;
          }
          
          /* --- Thermal Print Mode --- */
          @page {
             /* This is a suggestion; final size is controlled by the printer driver settings */
             size: 58mm auto; 
             margin: 4mm;
          }
          body.print-mode-thermal .thermal-print-container,
          body.print-mode-thermal .thermal-print-container * {
            visibility: visible;
          }
          body.print-mode-thermal .thermal-print-container {
            display: block !important;
            position: absolute !important;
            left: 0 !important;
            top: 0 !important;
            width: 100% !important; /* Let driver handle width */
          }
        }
      `}</style>
    </div>
  );
};

export default WeeklyReportModal;
